SHELL = /bin/sh
CC = gcc
CFLAGS = -Wall
LIBNAME = libsplgraph.a
LIBRARY_PATH = /usr/include/lib
OBJS = graph.o
HEADERS = graph.h
HEADER_PATH = /usr/include
RM = rm -f

$(LIBNAME): $(OBJS)
	$(AR) rcs $@ $^

install: $(LIBNAME)
	mkdir -p $(LIBRARY_PATH)
	cp $(LIBNAME) $(LIBRARY_PATH)/

headers: $(HEADERS)
	cp $(HEADERS) $(HEADER_PATH)

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) $(LIBNAME)