SHELL = /bin/sh
CC = gcc
CFLAGS = -Wall
LIBNAME = libsplds.so
OBJFILES = llist.o stack.o queue.o heap.o union_find.o
RM = rm -f

library: $(OBJFILES)
	$(CC) $(CFLAGS) -shared -o $(LIBNAME) $(OBJFILES)

llist.o: llist.h
stack.o: llist.h stack.h
queue.o: llist.h queue.h
heap.o: heap.h
union_find.o: union_find.h

install: library
	cp $(LIBNAME) /usr/local/lib

clean:
	$(RM) $(OBJFILES)

distclean: clean
	$(RM) $(LIBNAME)